test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: spree_marketing
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: spree_marketing
  host: localhost
  username: postgres
  password: postgress
  timeout: 5000